/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hhhhh;

/**
 *
 * @author jridi
 */
public class boite_envoi extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel1
     */
    public boite_envoi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel34 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jTextField46 = new javax.swing.JTextField();
        jCheckBox6 = new javax.swing.JCheckBox();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jPanel35 = new javax.swing.JPanel();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jPanel36 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();

        jPanel34.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel34.setLayout(null);

        jCheckBox1.setText("jCheckBox1");
        jPanel34.add(jCheckBox1);
        jCheckBox1.setBounds(30, 200, 20, 23);

        jCheckBox2.setText("jCheckBox1");
        jPanel34.add(jCheckBox2);
        jCheckBox2.setBounds(30, 40, 20, 23);

        jCheckBox3.setText("jCheckBox1");
        jPanel34.add(jCheckBox3);
        jCheckBox3.setBounds(30, 70, 20, 23);

        jCheckBox4.setText("jCheckBox1");
        jPanel34.add(jCheckBox4);
        jCheckBox4.setBounds(30, 110, 20, 23);

        jCheckBox5.setText("jCheckBox1");
        jPanel34.add(jCheckBox5);
        jCheckBox5.setBounds(30, 150, 20, 23);

        jTextField46.setText("À  ");
        jPanel34.add(jTextField46);
        jTextField46.setBounds(100, 200, 250, 20);

        jCheckBox6.setText("jCheckBox1");
        jPanel34.add(jCheckBox6);
        jCheckBox6.setBounds(30, 200, 20, 23);

        jTextField47.setText("À  ");
        jPanel34.add(jTextField47);
        jTextField47.setBounds(100, 40, 250, 20);

        jTextField48.setText("À  ");
        jPanel34.add(jTextField48);
        jTextField48.setBounds(100, 70, 250, 20);

        jTextField16.setText("À  ");
        jPanel34.add(jTextField16);
        jTextField16.setBounds(100, 110, 250, 20);

        jTextField17.setText("À  ");
        jPanel34.add(jTextField17);
        jTextField17.setBounds(100, 150, 250, 20);

        jPanel35.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        jPanel34.add(jPanel35);
        jPanel35.setBounds(10, 30, 890, 210);

        jButton35.setText("Renvoyer");
        jButton35.setActionCommand("Renvoyé");
        jPanel34.add(jButton35);
        jButton35.setBounds(390, 490, 80, 23);

        jButton36.setText("Lire");
        jPanel34.add(jButton36);
        jButton36.setBounds(170, 490, 80, 23);

        jButton37.setText("Supprimer");
        jPanel34.add(jButton37);
        jButton37.setBounds(600, 490, 81, 23);

        jPanel36.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        jPanel34.add(jPanel36);
        jPanel36.setBounds(10, 270, 890, 210);

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(204, 0, 204));
        jLabel57.setText("Messages Envoyés");
        jPanel34.add(jLabel57);
        jLabel57.setBounds(20, 10, 258, 15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    // End of variables declaration//GEN-END:variables
}
